### ISSUE TITLE
Tracking issue to add Pulsar scenarios 

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/pulsar-planet#1]
## Draws

* [x] Add Change Data Capture scenario picture
* [ ] Add Click Stream Agent scenario picture
* [ ] Add Log Appender scenario picture
* [ ] Add Streaming Analytics scenario picture
* [ ] Add Enterprise Service Bus scenario picture

## Descriptions

* [ ] Add Change Data Capture scenario description
* [ ] Add Click Stream Agent scenario description
* [ ] Add Log Appender scenario description
* [ ] Add Streaming Analytics scenario description
* [ ] Add Enterprise Service Bus scenario description

**Comment by tisonkun** [comment]
I'd prefer to use SVGs for pictures. However, it seems Excalidraw doesn't work well in SVG exports (perhaps on macOS only, perhaps related to Docusaurus framework).

* https://github.com/facebook/docusaurus/discussions/8021
