### ISSUE TITLE
Tracking issue for connecting to Pulsar

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/pulsar-planet#3]
Content is hosted under https://github.com/tisonkun/pulsar-planet/tree/main/connect.

## Clients

* [ ] Example to connect Pulsar cluster with Java Client
* [ ] Example to connect Pulsar cluster with Go Client
* [ ] Example to connect Pulsar cluster with Python Client
* [ ] Example to connect Pulsar cluster with C# Client
* [ ] Example to connect Pulsar cluster with C++ Client
* [ ] Example to connect Pulsar cluster with Node.js Client

## Connectors
